# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04de41480314c2567c6fe6a17c4a306d18190e2e83c1a30564bb422e9cd359b44bc2dae6c26da97a54f4801b1093e7cae4af929363e0bdd03956a94be66431b4

test:
  secret_key_base: a6a28cc40919c963b7286a0db62821735925203a97a0abaa2a942b14522c662803860c283097e635c72754a55e6d964a3b901603ce9fa81423ad69d287d0b59b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
